# Generated by Django 5.1.4 on 2025-02-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionSubastas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='auctions/'),
        ),
    ]
