# Generated by Django 5.1.4 on 2025-01-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionSubastas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
