# Generated by Django 5.1.4 on 2025-02-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionSubastas', '0002_alter_auction_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='is_active',
        ),
    ]
