# Generated by Django 5.1.4 on 2025-02-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0002_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
